# update homebrew
update

# upgrade already installed formulae
upgrade

# add repository
tap caskroom/cask

# Packages
# basic
install coreutils
install curl

# main shell & tools
install fish
install tmux
install vim --override-system-vi

# essential
install ack                        # grep successor
install ag                         # ack successor
install pv                         # pipe meter
install apg                        # password generator
install ncdu                       # disk usage
install xz                         # compression
install tree                       # tree generator
install jq                         # JSON processor
install multitail                  # tail hype
install ranger                     # file manager
install pigz                       # parallel gzip
install fzf                        # fuzzy finder
install ssh-copy-id

# development
install git
install tig                        # git cli browser
install gist                       # snippets
install gh                         # git+hub wrapper
#install bfg                       # git repo cleaner
#install gibo                      # gitignore boilerplates

# network
install curl                       # newest cURL
install wget
install nmap                       # security scanner
install mtr                        # better traceroute
install aria2                      # download utility
install swaks                      # SMTP tester
install spoof-mac                  # MAC addres spoofing
install knock                      # port knocking
install socat
install ngrep
install speedtest_cli              # speedtest

# encryption
install pass                       # password manager
install gnupg2                     # OpenPGP
install keybase                    # Key repository

# security
install john                       # cracker

# osx specific
install terminal-notifier

# other
install jrnl                       # shell notes

# Casks
# setup cask
install brew-cask

# install
#cask install cakebrew
#cask install yorufukurou         # twitter client

cleanup

